services:
    frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile
        env_file: ./.env
        container_name: frontend
        ports:
            - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT