# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cb8d7d94-9979-4dc0-8737-7ea7317a97b6'
  frontendImageRepository: 'dsrusudavidproduction-frontend'
  backendImageRepository: 'dsrusudavidproduction-backend'
  containerRegistry: 'containerregistrydavid30442.azurecr.io'
  frontendDockerfilePath: '$(Build.SourcesDirectory)/ds2022_30442_rusu_david_1_frontend/Dockerfile'
  backendDockerfilePath: '$(Build.SourcesDirectory)/DS2022_30442_Rusu_David_1_Backend/Dockerfile'
  tag: 'latest'

stages:
- stage: Build-backend
  displayName: Build and push backend-stage
  jobs:
  - job: Build
    displayName: Build backend
    pool:
      name: local
    steps:
    - task: Docker@2
      displayName: Build and push backend image to container registry
      inputs:
        command: buildAndPush
        repository: $(backendImageRepository)
        dockerfile: $(backendDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Build-frontend
  displayName: Build and push frontend-stage
  jobs:
  - job: Build
    displayName: Build frontend
    pool:
      name: local
    steps:
    - task: Docker@2
      displayName: Build and push frontend image to container registry
      inputs:
        command: buildAndPush
        repository: $(frontendImageRepository)
        dockerfile: $(frontedDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)